# Bootstrap the local DuckDB store

# Composes existing building blocks; no new business logic:
# 1. init_db (app.storage.db) — idempotent schema
# 2. batch_score (app.risk.batch) — score every production row with the frozen model and persist risk_predictions
# 3. generate_evidence  (app.evidence.service)    — warm deterministic evidence for the demo transaction
# 4. load the frozen v1 link table (data/processed/graph_links.parquet) into the store's graph_links table so case/EntityRisk queries see the same links the graph service serves from Parquet

# Run once after cloning so the API, the demo runner and the integration tests have a populated store: python scripts/bootstrap_db.py

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

DEMO_TXN = 3011051


def _require_real_data_prerequisites(settings) -> list[str]:
    # Return human-readable guidance for every missing prerequisite
    # The real-data store cannot be built from a data-free clone; this must fail clearly instead of mysteriously.
    from src.config import DATA_PROC

    checks = [
        (settings.reports_dir / "temporal_analysis.json",
         "chronological split anchors — run: python scripts/setup_data.py --build"),
        (DATA_PROC / "experiment_base.parquet",
         "modeling table — run: python scripts/setup_data.py --build"),
        (DATA_PROC / "graph_links.parquet",
         "frozen v1 link table — regenerable via scripts/setup_data.py --build"),
        (DATA_PROC / "production_features.parquet",
         ("production relational features — NOT generated by the public "
          "repository yet; supply locally (see scripts/setup_data.py)")),
        (settings.model_dir / "latest.json",
         "frozen model artifact — ships with the repository"),
        (Path(__file__).resolve().parents[1] / "frontend" / "dist" / "index.html",
         "frontend build — npm --prefix frontend ci && npm --prefix frontend run build"),
    ]
    return [msg for path, msg in checks if not path.exists()]


def main() -> int:
    from app.config import load_settings

    settings = load_settings()
    missing = _require_real_data_prerequisites(settings)
    if missing:
        print("Cannot bootstrap the real-data store: prerequisites missing.")
        for msg in missing:
            print(f"  - {msg}")
        print("\nIEEE-CIS/Vesta data is not included in this repository; see")
        print("README 'Data availability' and scripts/setup_data.py.")
        return 2

    from app.evidence.service import generate_evidence
    from app.risk.batch import batch_score
    from app.storage.db import init_db

    init_db(settings.db_path)
    print(f"schema ready: {settings.db_path}")

    result = batch_score(settings.processed_dir, settings.model_dir,
                         settings.db_path, settings.reports_dir)
    print(f"batch scoring: {result['rows_scored']} rows "
          f"in {result['batch_seconds']}s "
          f"(model {result['model_version']}, mean score {result['mean_score']})")

    _model_risk, evidence = generate_evidence(DEMO_TXN, settings)
    print(f"demo evidence warmed for txn {DEMO_TXN}: "
          f"{len(evidence)} records, types={sorted(e.evidence_type for e in evidence)}")

    from app.storage.db import connect
    conn = connect(settings.db_path)
    conn.execute("DELETE FROM graph_links")
    conn.execute("INSERT INTO graph_links SELECT * FROM read_parquet(?)",
                 [str(settings.processed_dir / "graph_links.parquet")])
    n_links = conn.execute("SELECT COUNT(*) FROM graph_links").fetchone()[0]
    conn.close()
    print(f"store graph_links loaded: {n_links} rows (frozen v1 table)")

    print("bootstrap complete")
    return 0


if __name__ == "__main__":
    sys.exit(main())
