# Public data setup for FraudGraph (download-first / data-gated)

# The IEEE-CIS Fraud Detection dataset (provided by Vesta Corporation via the Kaggle competition) is NOT included in this repository and is NOT redistributed by it. It is governed by its own competition/distribution terms, which every user must accept at the source. This script:
# 1. explains what is missing and why,
# 2. checks which local artifacts already exist,
# 3. refuses cleanly with actionable guidance when prerequisites are absent,
# 4. runs ONLY existing project generators where one exists,
# 5. never downloads the competition dataset,
# 6. never asks for credentials inside this repository,
# 7. never touches the frozen model artifacts.

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

KAGGLE_RULES_URL = "https://www.kaggle.com/competitions/ieee-fraud-detection/rules"

NO_GENERATOR_BLOCKER = (
    "BLOCKER: public repository has no committed generator for "
    "data/processed/production_features.parquet; implementing one would be new "
    "functionality and is outside this cleanup."
)


def _run(script: str) -> bool:
    print(f"\n>>> running existing generator: {script}")
    r = subprocess.run([sys.executable, str(ROOT / script)], cwd=ROOT,
                       check=False)
    return r.returncode == 0


def main() -> int:
    parser = argparse.ArgumentParser(description="FraudGraph real-data setup checker/builder")
    parser.add_argument("--build", action="store_true",
                        help="run existing generators for stages whose inputs are available")
    args = parser.parse_args()

    from src.config import DATA_PROC, IEEE_IDN_CSV, IEEE_TXN_CSV, REPORTS

    raw_ok = IEEE_TXN_CSV.exists() and IEEE_IDN_CSV.exists()
    txn_parquet = DATA_PROC / "ieee_train_transaction.parquet"
    idn_parquet = DATA_PROC / "ieee_train_identity.parquet"
    temporal = REPORTS / "temporal_analysis.json"
    exp_base = DATA_PROC / "experiment_base.parquet"
    graph_links = DATA_PROC / "graph_links.parquet"
    prod_features = DATA_PROC / "production_features.parquet"

    def build_graph_links() -> bool:
        # Existing project function; verified to reproduce the frozen v1 link
        # table content (254,777 rows) deterministically from experiment_base.
        from app.graph.build import build_graph_links
        result = build_graph_links(exp_base, graph_links)
        print(f"graph links rebuilt: {result['rows']} rows "
              f"({result['entities']} entities in {result['build_seconds']}s)")
        return True

    print("=" * 72)
    print("FRAUDGRAPH REAL-DATA SETUP (IEEE-CIS / Vesta)")
    print("=" * 72)
    if not raw_ok:
        print(f"""
The competition dataset is NOT included in this repository and is NOT
redistributed by it. To use the real-data investigation flow you must obtain
it yourself from an authorized source, e.g.:

  1. create a Kaggle account;
  2. read and accept the competition rules: {KAGGLE_RULES_URL}
  3. download train_transaction.csv and train_identity.csv;
  4. place both files under:  {ROOT / 'IEEE-CIS Fraud Detection'}

(equivalently, use the Kaggle CLI yourself with your own credentials;
this repository never embeds or asks for credentials).

Code licensing (see LICENSE) and dataset distribution terms are separate.
""")
    else:
        print("Raw competition CSVs found (locally obtained). OK.\n")

    rows: list[tuple[str, str, str]] = []
    rows.append(("raw CSVs", str(IEEE_TXN_CSV.parent), "present" if raw_ok else "MISSING"))
    rows.append(("ieee caches", f"{txn_parquet.name}, {idn_parquet.name}",
                 "present" if txn_parquet.exists() else "absent (generator: scripts/import_ieee.py)"))
    rows.append(("temporal anchors", temporal.name,
                 "present" if temporal.exists() else "absent (generator: scripts/temporal_analysis.py)"))
    rows.append(("experiment_base", exp_base.name,
                 "present" if exp_base.exists() else "absent (generator: scripts/build_modeling_table.py)"))
    rows.append(("graph_links", graph_links.name,
                 "present" if graph_links.exists()
                 else "absent (regenerable via app.graph.build.build_graph_links)"))

    print(f"{'stage':<18} {'artifact(s)':<42} status")
    print("-" * 100)
    for name, arts, status in rows:
        print(f"{name:<18} {arts:<42} {status}")

    prod_status = ("present" if prod_features.exists()
                   else "NOT GENERATED BY THE PUBLIC REPOSITORY")
    print(f"{'production_feats':<18} {prod_features.name:<42} {prod_status}")

    if args.build:
        if not raw_ok:
            print("\nRefusing to build: raw competition CSVs are not present locally.")
            return 1
        ok = True
        if not txn_parquet.exists():
            ok &= _run("scripts/import_ieee.py")
        if not temporal.exists():
            ok &= _run("scripts/temporal_analysis.py")
        if not exp_base.exists() and temporal.exists():
            ok &= _run("scripts/build_modeling_table.py")
        if not graph_links.exists() and exp_base.exists():
            try:
                ok &= build_graph_links()
            except Exception as exc:  # noqa: BLE001 - report, never fabricate
                print(f"graph_links regeneration failed: {exc}")
                ok = False
        if not ok:
            print("\nOne or more generator steps failed; see output above.")
            return 1

    complete = all(Path(p).exists() for p in
                   (txn_parquet, temporal, exp_base, graph_links, prod_features))
    if not prod_features.exists():
        print(f"\n{NO_GENERATOR_BLOCKER}")
        print("Until a generator is committed, supply that artifact locally "
              "(e.g. from your original working environment); it stays "
              "gitignored either way.")
    if not complete:
        print("\nReal-data path INCOMPLETE. After completing the artifacts:")
        print("  set FG_REAL_DATA=1 and run: python -m pytest tests -q")
        print("  then: python scripts/bootstrap_db.py && python scripts/run_demo.py")
        return 1

    print("\nAll real-data artifacts present. Full validation:")
    print("  set FG_REAL_DATA=1 and run: python -m pytest tests -q")
    print("  python scripts/bootstrap_db.py")
    return 0


if __name__ == "__main__":
    sys.exit(main())
